import random
import secp256k1

prikey = 0x5f6717883bef25f45a129c11fcac1567d74bda5a9ad4cbffc8203c0da2a1473c
pubkey = secp256k1.G * prikey

# Hash of messages. Generated by "sha256sum secp256k1.py"
m = 0x72a963cdfb01bc37cd283106875ff1f07f02bc9ad6121b75c3d17629df128d4e
print(f'hash=0x{m:064x}')

# Sign
while True:
    k = random.randint(0, secp256k1.N)
    R = secp256k1.G * k
    r = R.x.x % secp256k1.N
    if r == 0:
        continue
    k_inv = pow(k, -1, secp256k1.N)
    s = ((m + prikey * r) * k_inv) % secp256k1.N
    if s == 0:
        continue
    print(f'sigr=0x{r:064x}')
    print(f'sigs=0x{s:064x}')
    break


# Verify
assert 0 <= r < secp256k1.N
assert 0 <= s < secp256k1.N
w = pow(s, -1, secp256k1.N)
u1 = (m * w) % secp256k1.N
u2 = (r * w) % secp256k1.N
x = secp256k1.G * u1 + pubkey * u2
if x == secp256k1.I:
    print('fail')
v = x.x.x % secp256k1.N
assert v == r
print('pass')
